### ISSUE TITLE
I need  Ocaml 4.02

### ISSUE THREAD

**Issue by jmgbsas** [dra27/OCaml-Windows-Build#1]
I need Ocaml 4.02 to build Haxe, How I can do it?
Could I download another version and all will run ok?

https://github.com/HaxeFoundation/haxe/blob/development/extra/BUILDING.md

Thanks

**Comment by dra27** [comment]
I’m not sure how you ended up here - the instructions you link to have references to the installers for opam. I’ve never used Haxe, but I see it has both binary installers (referenced in its README) and requires OCaml 4.02 _or higher_.

If you have any other questions about OCaml, I’d recommend heading over to OCaml’s [discuss forum](https://discuss.ocaml.org)
